# Generated by Django 3.2.8 on 2021-10-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_customerorder_customer'),
        ('invoice', '0002_auto_20211025_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('customer', 'customer_order')},
        ),
    ]
