# Generated by Django 3.2.8 on 2021-10-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.customerorder')),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.storeitem')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
    ]
