# Generated by Django 3.2.8 on 2021-10-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20211025_1217'),
        ('order', '0002_customerorder_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.customer'),
            preserve_default=False,
        ),
    ]
